### ISSUE TITLE
Cannot find module './computeDestinationPoint' 

### ISSUE THREAD

**Issue by amexboy** [manuelbieh/geolib#308]
I am getting

 ```Cannot find module './computeDestinationPoint' Require stack: - /home/xxx/projects/xxx/geolib```
 
 This only happens on versions 3.3.2 and up. I was able to get it to work on 3.3.1. I can't quite see why

**Comment by geofany** [comment]
same here

**Comment by syl-p** [comment]
same here using geolib in a nuxt project.

**Comment by karottenreibe** [comment]
same here. downgrading to 3.3.1 did not resolve the issue for me
